application: hello-webpy
version: 1
api_version: 1
runtime: python

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: https://webpy.org/cookbook/helloworld
  script: hello.py
